<?php

/**
 * @Author: Phu Hoang
 * @Date:   2016-01-11 13:19:26
 * @Last Modified by:   Phu Hoang
 * @Last Modified time: 2016-02-16 18:33:25
 */

namespace hmphu\payoneer;

/**
 * Class PayoneerApi
 * @package hmphu\payoneer
 */
class PayoneerApi extends ApiAbstract
{
	
    /**
     * @param PayoneerConfig $config
     */
    function __construct(PayoneerConfig $config) {
    	parent::__construct($config);
    }
    
    /**
     * The token is unique and is generated by Payoneer specifically for each sign-up session.
     *
     * @param PayeeSignupRequest $request
     * @throws \Exception
     * @return array
     */
    public function getToken(request\PayeeSignupRequest $request) {
    	$this->call('GetToken', $request);
    	$response = new response\PayeeSignupResponse($this->response);
    	return $response->getData();
    }
    
    /**
     * The token is unique and is generated by Payoneer specifically for each sign-up session.
     *
     * @param PayeeSignupAutoPopulationRequest $request
     * @throws \Exception
     * @return array
     */
    public function getTokenXML(request\PayeeSignupAutoPopulationRequest $request) {
    	$this->call('GetTokenXML', $request);
    	$response = new \response\PayeeSignupAutoPopulationResponse($this->response);
    	return $response->getData();
    }
    
    /**
     * This method provides the status of the API and payout
     * services (Heart Beep).
     *
     * @return mixed
     */
    public function getApiStatus() {
    	$this->call('Echo', new request\BasicRequest());
    	$response = new response\BasicResponse($this->response);
    	return $response->getData()['Description'];
    }
    
    /**
     * This method provides the API version.
     *
     * @return mixed
     */
    public function getVersion() {
    	$this->call('GetVersion', new request\BasicRequest());
    	$response = new response\BasicResponse($this->response);
    	return $response->getData()['Version'];
    }
    
    /**
     * This method, if successful, creates a payment request
     * in the Payoneer system. Prior to issuing payment
     * instructions, the partner’s account balance in the
     * Payoneer system must be credited relative to the
     * payment request. Payout instruction submission will
     * fail if the partner’s account balance does not have
     * sufficient funds to perform the account loads. In
     * addition the payee ID must be active.
     *
     * @param PerformPayoutPaymentRequest $request
     * @return mixed
     */
    public function performPayoutPayment(request\PerformPayoutPaymentRequest $request) {
    	$this->call('PerformPayoutPayment', $request);
    	$response = new response\PerformPayoutPaymentResponse($this->response);
    	return $response->getData();
    }
    
    /**
     * This method, if successful, reports the status of a
     * payment that was earlier sent to the Payoneer system.
     *
     * @param $payeeId
     * @param $paymentId
     * @return mixed
     */
    public function getPaymentStatus($payeeId, $paymentId) {
    	$request = new request\GetPaymentStatusRequest($payeeId, $paymentId);
    	$this->call('GetPaymentStatus', $request);
    	$response = new response\GetPaymentStatusResponse($this->response);
    	return $response->getData();
    }
    
    /**
     * This method returns the partner’s available account balance.
     *
     * @return mixed
     */
    public function getAccountDetails() {
    	$request = new request\BasicRequest();
    	$this->call('GetAccountDetails', $request);
    	$response = new response\GetAccountDetailsResponse($this->response);
    	return $response->getData();
    }
    
    /**
     * This method returns details about the requested
     * payee and his status at Payoneer.
     *
     * @param $payeeId
     * @return mixed
     */
    public function getPayeeDetails($payeeId) {
    	$request = new request\PayeeRequest($payeeId);
    	$this->call('GetPayeeDetails', $request);
    	$response = new response\GetPayeeDetailsResponse($this->response);
    	return $response->getData();
    }
    
    /**
     * This method changes the ID of an existing
     * payee (old) to a new one.
     *
     * @param $oldId
     * @param $newId
     * @return mixed
     */
    public function changePayeeId($oldId, $newId) {
    	$request = new request\ChangePayeeIdRequest($oldId, $newId);
    	$this->call('ChangePayeeID', $request);
    	$response = new response\ChangePayeeIDResponse($this->response);
    	return $response->getData();
    }
    
    /**
     * This method returns all payments made to payees,
     * grouped by payment method.
     *
     * @param $startDate
     * @param $endDate
     * @return mixed
     */
    public function getPayeesReport($startDate, $endDate) {
    	$request = new request\GetPayeesReportRequest($startDate, $endDate);
    	$this->call('GetPayeesReport', $request);
    	$response = new response\GetPayeesReportResponse($this->response);
    	return $response->getData();
    }
    
    /**
     * This method returns all payments made to a single payee.
     *
     * @param $payeeId
     * @return mixed
     */
    public function getSinglePayeeReport($payeeId) {
    	$request = new request\PayeeRequest($payeeId);
    	$this->call('GetSinglePayeeReport', $request);
    	$response = new response\GetSinglePayeeReportResponse($this->response);
    	return $response->getData();
    }
    
    /**
     * This method returns an array of all payments that have
     * not yet been claimed.
     *
     * @return mixed
     */
    public function getUnclaimedPayments() {
    	$request = new request\BasicRequest();
    	$this->call('GetUnclaimedPaymentsXML', $request);
    	$response = new response\GetUnclaimedPaymentsResponse($this->response);
    	return $response->getData();
    }
    
    /**
     * This method returns a CSV string of all payments that have
     * not yet been claimed.
     *
     * @return string
     */
    public function getUnclaimedPaymentsCSV() {
    	$request = new request\BasicRequest();
    	$this->call('GetUnclaimedPaymentsCSV', $request);
    	$response = new response\GetUnclaimedPaymentsCSVResponse($this->response);
    	return $response->getData();
    }

    /**
     * This method returns a CSV string of all payments that have
     * not yet been claimed.
     *
     * @return string
     */
    public function movePayeeProgram() {
    	$request = new request\MovePayeeProgramRequest();
    	$this->call('movepayeeprogram', $request);
    	$response = new response\MovePayeeProgramResponse($this->response);
    	return $response->getData();
    }
    
    /**
     * This method cancels a payment that has not yet been
     * processed and loaded to an account.
     *
     * @param $paymentId
     * @return mixed
     */
    public function cancelPayment($paymentId) {
    	$request = new request\BasicPaymentRequest($paymentId);
    	$this->call('CancelPayment', $request);
    	$response = new response\CancelPaymentResponse($this->response);
    	return $response->getData();
    }
}
